name: Pokedex Deployment to Azure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Build the application and store the distribution files
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      # Persist the dist folder for subsequent jobs (test/e2e)
      - name: Upload Build Artifact 
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  # Run unit and integration tests
  test:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install dependencies
        run: npm ci
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Test
        run: npm test
  # Run end-to-end tests using Cypress
  e2e:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install dependencies
        run: npm ci
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: E2E Test
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:e2e
          start: npm run start-test
          wait-on: 'http://localhost:5000'

  # Build Docker image and push it to AWS ECR
  build-and-push:
    needs: [test, e2e] # Ensure deployment only happens if all tests pass
    runs-on: ubuntu-22.04
    # Execute only on pushes to main, not on pull requests
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Azure login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
